### ISSUE TITLE
wall parameter does not display "attachments" in comments

### ISSUE THREAD

**Issue by LdieSU7** [Rast1234/VOffline#3]
version 0.2 does not work
0.1 works

the Wall parameter is not complete.
can you make all links to additional materials "attachments" be attached, and not:

02/21/2021 9:52:54 606987899
Text
likes =, attachments = 1, id = 1309

"attachments" should contain "video-000000000_000000000", "photo", "doc"

**Comment by Rast1234** [comment]
i tkink i'm going to rewrite it again and support more attachment types and stuff...

**Comment by LdieSU7** [comment]
собсн паблик https://vk.com/59cmvwd , там есть https://vk.com/wall-174910236_4 , мне надо все комментарии извлечь в подобие такого +/-:
[new_314_2020-12-20_041254 (1).txt](https://github.com/Rast1234/VOffline/files/6022872/new_314_2020-12-20_041254.1.txt)

а получить могу только:
[comments.txt](https://github.com/Rast1234/VOffline/files/6022875/comments.txt)

т.е вместо https://vk.com/video-174910236_456240004?list=42dae382465b70ac53 , вижу только "attachments=1"
а сам каталог выглядит этого поста так:
![image](https://user-images.githubusercontent.com/62698341/108727524-bbd7cd80-7539-11eb-8a72-308d43b5504b.png)

**Comment by Rast1234** [comment]
спасибо за примеры, ща посмотрим...

**Comment by LdieSU7** [comment]
> спасибо за примеры, ща посмотрим...

а версия 0.2 у меня не работает:

> 0.1 works

```
2021-02-22 15:49:42,758 [  1] DEBUG  FileCache.VkToken.json saved value
2021-02-22 15:49:42,883 [  8] DEBUG  Processing ["Wall"] for [club174910236 -174910236]
2021-02-22 15:49:42,884 [  8] FATAL  System.IO.FileNotFoundException: Could not find file 'E:\My\Download\Browser\GoogleChrome\Profileremote\publish\publish\.cache.voffline'.
File name: 'E:\My\Download\Browser\GoogleChrome\Profileremote\publish\publish\.cache.voffline'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at VOffline.Services.Storage.FilesystemTools.LoadCache(ILog log) in C:\vault\VOffline\VOffline\Services\Storage\FilesystemTools.cs:line 36
   at VOffline.Services.Logic.Run(CancellationToken token, ILog log) in C:\vault\VOffline\VOffline\Services\Logic.cs:line 72
   at VOffline.Program.Main(String[] args) in C:\vault\VOffline\VOffline\Program.cs:line 88
```

**Comment by Rast1234** [comment]
да это мелкая бага, поправлю, сам столкнулся щас

**Comment by Rast1234** [comment]
пробуй https://github.com/Rast1234/VOffline/releases/tag/0.3
урл к видео сохраняется в файл внутри каждого коммента (так было сделать проще всего чтобы не переделывать)
если надо вывести все урлы из этих файлов то можно сделать так (на скринах был powershell поэтому пример для него)

```ps
Get-ChildItem '2018-12-05T23_37_26 2' -Filter *.txt -Recurse | Get-Content -encoding utf8
```
тут 2018-... это имя папки с постом

**Comment by LdieSU7** [comment]
я не совсем понял что ты скинул написав команду для powershell. типо что она должна делать?))
собсн я все объединил в одном блокноте с помощью total commander:
1. сналача все блокноты переименовал в название папок [P]
2. стер все лишнее [N21-24]
3. скопировал все блокноты в общую папку. отобразил все с помощью функции "показать все файлы без подкаталогов", выделил все, скопировал.
4. прописал в каждом блокноте название файла. 
создал "cmd" файл начинающийся с "chcp 1251 >nul", следующими строчками было вывод из excel содержимого:
первая колонка (до конца вниз): "echo  "(два пробела) 
вторая и четвертая колонка: скопированные имена файлов без .txt
третья колонка: ">>"
пятая: скопированные имена файлов
затем отформатировал примерно как описал: `echo ‌‌‍ 346 >>346.txt`
5. объединил все файлы через total commander: Все файлы сортировать по имени (метод сортировки: "Естественная сортировка: коды символов и числа"), счетчик [C], цифр "5"; выбрать файл 00001.txt - файлы - "Собрать файлы..."

..
ну и собсн у столкнулся с незнанием как сопоставить "id=" с "comments.txt"?))
общее там "id=**346**" из "comments.txt"
и "2020-12-16T18_05_42 **346**" из названия папок
[comments.txt](https://github.com/Rast1234/VOffline/files/6023848/comments.txt)
[00000.txt](https://github.com/Rast1234/VOffline/files/6023849/00000.txt)

**Comment by Rast1234** [comment]
пример на повершелле находит все .txt файлы и вываливает их в консоль подряд. ну это просто пример, кому как удобнее.

я не понимаю что ты хочешь сделать и с тотал командером не знаком, поэтому тут не подскажу.

**Comment by LdieSU7** [comment]
не нужен total commander
с помощью чего можно сопоставить данные из двух блокнотов?
там **общее** id=цифры
может в cmd? я прост хз))

**Comment by Rast1234** [comment]
cmd пригоден разве что чтобы запускать что-нибудь, парсить с его помощью файлы и что-то делать - боль и унижение(

тебе подойдут python или powershell

**Comment by LdieSU7** [comment]
> cmd пригоден разве что чтобы запускать что-нибудь, парсить с его помощью файлы и что-то делать - боль и унижение(
> 
> тебе подойдут python или powershell

.. сопоставил с помощью excel , функция ВПР
[1.txt](https://github.com/Rast1234/VOffline/files/6024053/1.txt)
[Книга2.xlsx](https://github.com/Rast1234/VOffline/files/6024054/2.xlsx)

**Comment by Rast1234** [comment]
ну то есть все работает?)

**Comment by LdieSU7** [comment]
_более менее_, но приходится все через одно место подгонять в читаемый вид. 

по идеи в этих папках "2021-02-07T11_57_26 1294" которые в каталоге comments должны быть .mp4 и другие файлы... но мне просто не нужно было их скачивать. однако те кому нужно их скачать столкнутся с некоторыми трудностями.  если рассматривать мой пример, то все видео БЕЗЫМЯННЫ, т.е я даже не представляю через что скачивать чтобы приобрели нормальный вид.

видео конечн качать так ебанешься(нужно отдельные параметры в appsettings), там гигов больше нескольких сотен будет(только в моем примере), а вот фоточки, doc(есть некоторые случаи когда могут прикреплять 100+гб. вот пример https://vk.com/wall-188576299_126 ), аудио должно справляться. но я не экспериментировал.

надеюсь что ты пофиксел не только линки от видео, а также и других типов документов
![image](https://user-images.githubusercontent.com/62698341/108749844-5d1e4e00-7551-11eb-999f-237e05d71bc4.png)

и также я хз как сопоставлять если будет несколько прикрепленных материалов, наверное все съедет и **этот способ с excel не подойдет**.

желательно конечно чтобы это уже было встроено, т.е в "comments.txt" были все ссылки (примерно как в 1.txt блокноте что я выше скилну), а в папках файлы, - надо скачивать/нет, в параметрах "appsettings.json"

**Comment by LdieSU7** [comment]
и еще вопрос. можно ли как-то настроить таким образом, чтобы качало только с конкретного поста)диапазона времени)? а не весь паблик

**Comment by LdieSU7** [comment]
и еще нужна поддержка обсуждений. а то их никак не скачать(

**Comment by Rast1234** [comment]
ну... я пофиксил только ссылки на видосы, и то костылем - видео же может быть выложено на любом хостинге (вк, ютуб, рутуб, вимео, и тд), сделать их скачивание я не осилю.

простой контент, который лежит прямо у вконтакта и он дает на него прямую ссылку, типа аттачей-картинок, вроде бы скачивается. ссылок на такой контент я вроде не пишу в файлы, потому что нафига если они скачаны будут)

диапазон был в прошлой версии но я заколебался с ним работать, поэтому тут не делал. по идее, если ты запускал утилиту вчера, потом запостил что-то, и запустил сегодня, то она должна докачивать новое, а не все подряд.

обсуждения не делал, да и много чего еще. хз когда сделаю, если честно
